Repository CISOfy/lynis, pull requests merged in 2020-03, with the labels that each got.

#850 Soerelease
  include/osdetection
  include/parameters
  lynis
Labels: enhancement

#840 Remove the test for ssh config VerifyReverseMapping
  include/tests_ssh
Labels: no-pr-activity

#843 Update tests_ports_packages
  include/tests_ports_packages
Labels: bug

#846 Update tests_shells
  include/tests_shells
Labels: no-pr-activity

#842 add basic xbps/void support
  include/binaries
  include/functions
Labels: enhancement

#829 AUTH-9228 for HP-UX
  include/tests_authentication
Labels: enhancement

#853 Skip the PHP cli configuration file when looking for expose_php
  CHANGELOG.md
  include/tests_php
Labels: needs-confirmation

#830 restructered test and fixed vmlinuz detection
  include/tests_kernel
Labels: enhancement

#845 [SSH-7408] fix OpenSSH server version check
  include/tests_ssh
Labels: no-pr-activity

#869 Add AUTH-9234 for NetBSD
  include/tests_authentication
Labels: needs-confirmation

#824 Add detection of OpenNTPD
  include/binaries
  include/tests_time
Labels: enhancement

#887 AUTH-9229 Do not use long options for sort
  include/tests_authentication
Labels: enhancement
